### ISSUE TITLE
Add Installation guidelines in the readme

### ISSUE THREAD

**Issue by phish108** [dimstudio/visual-inspection-tool#1]
Hi @dimstudio 

I tried to install your little inspection tool, but failed hopelessly. Could you please add some guidelines to the readme?

Thanks 
Christian

**Comment by dimstudio** [comment]
Thanks, Christian for the suggestion. I added a readme I hope it's clear enough!

**Comment by Titogelo** [comment]
It worked for me! Looks much much better than last time I had a look it. 

Congrats @dimstudio!
